# Generated by Django 6.0.5 on 2026-09-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_sanitize_content'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='Article',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
    ]
