# Generated by Django 6.0.5 on 2026-09-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_english_table_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
